<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accès sécurisé</title>
    <style>
        body {
            margin:0;
            background:black;
            color:white;
            font-family:monospace;
            text-align:center;
        }
        canvas {
            position:fixed;
            top:0;
            left:0;
            width: 100%;
            height: 100%;
            z-index: -1;
        }
        #login {
            margin-top: 20vh;
        }
        input {
            padding: 10px;
            font-size: 1.2em;
            border: none;
            outline: none;
        }
        button {
            padding: 10px 20px;
            font-size: 1.2em;
            cursor: pointer;
        }
        #content {
            display: none;
        }
    </style>
</head>
<body>
    <canvas id="matrix"></canvas>
    <div id="login">
        <h1>Entrez le mot de passe</h1>
        <input type="password" id="password" placeholder="Mot de passe">
        <button onclick="checkPassword()">Valider</button>
    </div>
    <div id="content">
        <h1>Bienvenue !</h1>
        <p>Vous avez accédé au contenu protégé.</p>
    </div>
    <script>
        const correctPassword = "secret123";
        function checkPassword() {
            const input = document.getElementById("password").value;
            if (input === correctPassword) {
                document.getElementById("login").style.display = "none";
                document.getElementById("content").style.display = "block";
            } else {
                alert("Mot de passe incorrect !");
            }
        }
        const canvas = document.getElementById("matrix");
        const ctx = canvas.getContext("2d");
        canvas.width = window.innerWidth;
        canvas.height = window.innerHeight;
        const words = ["MATTHIEU", "STREET WORKOUT", "PIANO", "BASSON", "SFX1", "GIN", "HOCKEY", "LOUVETEAUX", "INGÉNIEUR", "ARMÉE", "ART", "ENGAGEMENT", "TOURNOI D'ÉLOQUENCE", "AGENT SECRET", "BEN10", "MATRIX", "KETUPA", "INDIANA JONES"];
        const letters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789@#$%^&*()*&^%".split("").concat(words);
        const fontSize = 16;
        const columns = canvas.width / fontSize;
        const drops = Array(Math.floor(columns)).fill(0);
        function drawMatrix() {
            ctx.fillStyle = "rgba(0, 0, 0, 0.05)";
            ctx.fillRect(0, 0, canvas.width, canvas.height);
            ctx.fillStyle = "#0F0";
            ctx.font = `${fontSize}px monospace`;
            for (let i = 0; i < drops.length; i++) {
                const text = letters[Math.floor(Math.random() * letters.length)];
                ctx.fillText(text, i * fontSize, drops[i] * fontSize);
                if (drops[i] * fontSize > canvas.height && Math.random() > 0.975) {
                    drops[i] = 0;
                }
                drops[i]++;
            }
        }
        setInterval(drawMatrix, 50);
    </script>
</body>
</html>
